# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('endereco', models.IntegerField(verbose_name='endereco')),
                ('cep', models.CharField(max_length=8, verbose_name='cep')),
                ('telefone', models.CharField(max_length=9, verbose_name='telefone')),
                ('cidade', models.CharField(max_length=200, verbose_name='cidade')),
                ('estado', models.CharField(max_length=200, verbose_name='estado')),
            ],
        ),
    ]
