# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('autores', models.TextField(verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculo', models.CharField(max_length=200, verbose_name='curriculo')),
                ('artigos', models.TextField(verbose_name='Artigo')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('eventoPrincipal', models.CharField(max_length=200, verbose_name='evento rincipal')),
                ('sigla', models.CharField(max_length=50, verbose_name='sigla')),
                ('dataEHoraDeInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data e hora de inicio')),
                ('palavrasChave', models.CharField(max_length=200, verbose_name='palavras chave')),
                ('logotipo', models.CharField(max_length=200, verbose_name='logotipo')),
                ('cidade', models.CharField(max_length=200, verbose_name='cidade')),
                ('uf', models.CharField(max_length=200, verbose_name='uf')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('cep', models.DateTimeField(max_length=200, verbose_name='cep')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=200, verbose_name='issn')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=200, verbose_name='cpf')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=200, verbose_name='cnpj')),
                ('razaoSocial', models.CharField(max_length=200, verbose_name='cnpj')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='autor',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EventoCientifico'),
        ),
    ]
