# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigocientifico',
            options={'verbose_name': 'artigo cientifico', 'verbose_name_plural': 'artigos cientificos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='eventoPrincipal',
            field=models.CharField(max_length=200, verbose_name='evento principal'),
        ),
    ]
